CREATE DATABASE QLPKS
go
USE QLPKS
go
 
 CREATE TABLE TAIKHOAN
(
 TENTK VARCHAR(50) NOT NULL,
 MATKHAU VARCHAR(50) NOT NULL,
 NHAPLAIMK VARCHAR(50)
 )
 go
 CREATE TABLE DICHVU
(
 MADV INT IDENTITY(900,1) NOT NULL,
 TENDV NVARCHAR(50) NOT NULL,
 GIADV float,
 GHICHU NVARCHAR(500),
 
 CONSTRAINT pk_DICHVU PRIMARY KEY (MADV)
 )
 go

 CREATE TABLE PHONG
(
 MAPHONG INT IDENTITY(100,10) NOT NULL,
 TENPHONG NVARCHAR(50) NOT NULL,
 LOAIPHONG NVARCHAR(20) NOT NULL,-->1 giuong din,2 giuong don,...
 GIAPHONG FLOAT	,
 CHUTHICH NVARCHAR(100),
 TINHTRANG NVARCHAR(50),-->trong,dang su dung...
 MADV INT,
 NGAYTHUE VARCHAR(50),
 NGAYTRAPHONG VARCHAR(50),
 MAKH int,
 CONSTRAINT pk_PHONG PRIMARY KEY (MAPHONG),
 CONSTRAINT fk_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
)
go
  CREATE TABLE LOAIKH
(
 MALOAIKH INT IDENTITY(800,1) NOT NULL,
 TENLOAIKH NVARCHAR(50) NOT NULL,
 TIENGIAM float,
 MOTA NVARCHAR(500),
 
 CONSTRAINT pk_LOAIKH PRIMARY KEY (MALOAIKH)
 )
 go
CREATE TABLE KHACHHANG
(
 MAKH INT IDENTITY(700,1) NOT NULL,
 TENKH NVARCHAR(50) NOT NULL,
 CMND VARCHAR(20) NOT NULL,
 QUOCTICH NVARCHAR(50),
 GIOITINH NCHAR(3),
 TUOI INT,
 SDT VARCHAR(20),
 MAPHONG INT,
 MALOAIKH INT,

 CONSTRAINT pk_KHACHHANG PRIMARY KEY (MAKH),
 CONSTRAINT fk_LOAIKH FOREIGN KEY (MALOAIKH) REFERENCES LOAIKH(MALOAIKH),
 CONSTRAINT fk_PHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
 )
 go
 CREATE TABLE HOADON
(
 MAHD INT IDENTITY(600,1) NOT NULL,
 MAPHONG INT,
 NGAY VARCHAR(50),
 GIAHD FLOAT,
 CONSTRAINT pk_HOADON PRIMARY KEY (MAHD),
 CONSTRAINT fk_PHONG2 FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
 )
 go
 alter table PHONG
	add constraint fk_DICHVU
		FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
		on delete cascade
		on update cascade
 alter table KHACHHANG
	add constraint fk_LOAIKH 
		FOREIGN KEY (MALOAIKH) REFERENCES LOAIKH(MALOAIKH)
		on delete cascade
		on update cascade,
		constraint fk_PHONG 
		FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
		on delete cascade
		on update cascade
 alter table HOADON
	add constraint fk_PHONG2 
		FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
		on delete cascade
		on update cascade

















