/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.DBConnection;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author GuynIT
 */
public class DatPhong extends javax.swing.JPanel {

    /**
     * Creates new form DatPhong
     */
    public DatPhong() {
        initComponents();
        CrudTable();
        PHONG();
        DICHVU();
        KHACHHANG();
    }
    
    Connection con = DBConnection.getConnection();
    PreparedStatement pst;
    ResultSet rs;
    
    public void CrudTable()
    {
        try {
            pst = con.prepareStatement("select * from PHONG ");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData RSM = rs.getMetaData();
            int c;
            c = RSM.getColumnCount();
            
            DefaultTableModel DF = (DefaultTableModel)tbl_DSThuePhong.getModel();
            
            DF.setRowCount(0);
            
            while(rs.next())
            {    
                Vector v2 = new Vector();
                for(int i=1; i <= c; i++)
                {
                    v2.add(rs.getString("MAPHONG"));
                    v2.add(rs.getString("MAKH"));
                    v2.add(rs.getString("MADV"));
                    v2.add(rs.getString("NGAYTHUE"));
                    v2.add(rs.getString("NGAYTRAPHONG"));
                }
                DF.addRow(v2);
            }   
        } catch (SQLException ex) {
            Logger.getLogger(DatPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DSThuePhong = new javax.swing.JTable();
        lbl_DSThuePhong = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        thuephong = new javax.swing.JLabel();
        tenkh = new javax.swing.JLabel();
        phong = new javax.swing.JLabel();
        ngaythue = new javax.swing.JLabel();
        ngayra = new javax.swing.JLabel();
        cbb_KhachHang = new javax.swing.JComboBox<>();
        btnDatPhong = new javax.swing.JButton();
        dateTra = new com.toedter.calendar.JDateChooser();
        dateThue = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        phong1 = new javax.swing.JLabel();
        cbxMaPhong = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        pnl.setBackground(new java.awt.Color(204, 255, 204));
        pnl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbl_DSThuePhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Mã khách hàng", "Mã dịch vụ", "Ngày thuê", "Ngày trả"
            }
        ));
        tbl_DSThuePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DSThuePhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_DSThuePhong);

        lbl_DSThuePhong.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        lbl_DSThuePhong.setText("Danh sách đã đặt phòng");

        pnl2.setBackground(new java.awt.Color(204, 204, 255));

        thuephong.setBackground(new java.awt.Color(204, 255, 204));
        thuephong.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        thuephong.setForeground(new java.awt.Color(255, 102, 204));
        thuephong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thuephong.setText("ĐẶT PHÒNG");
        thuephong.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 204), new java.awt.Color(255, 204, 204)));

        tenkh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenkh.setText("Mã khách hàng");

        phong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phong.setText("Mã phòng");

        ngaythue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ngaythue.setText("Ngày thuê");

        ngayra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ngayra.setText("Ngày ra dự kiến");

        cbb_KhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnDatPhong.setBackground(new java.awt.Color(204, 0, 51));
        btnDatPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDatPhong.setText("Đặt phòng");
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã dịch vụ");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("   ");
        jScrollPane3.setViewportView(jTextArea2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Chú thích:");

        phong1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbxMaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thuephong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(phong1)
                .addGap(18, 18, 18)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ngaythue, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ngayra, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tenkh, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(phong, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_KhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(dateThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxMaPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGap(118, 118, 118))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thuephong)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(phong1))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phong))
                        .addGap(23, 23, 23)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbb_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenkh))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngaythue)
                            .addComponent(dateThue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngayra)
                            .addComponent(dateTra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(63, 63, 63)
                .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lbl_DSThuePhong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(lbl_DSThuePhong)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 864, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_DSThuePhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DSThuePhongMouseClicked
        DefaultTableModel d1 = (DefaultTableModel)tbl_DSThuePhong.getModel();
        int SelectIndex = tbl_DSThuePhong.getSelectedRow();
        
        String MaPhong = d1.getValueAt(SelectIndex, 0).toString();
 
    }//GEN-LAST:event_tbl_DSThuePhongMouseClicked

    private void PHONG(){
        String sql = "select * from PHONG";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                cbxMaPhong.addItem(rs.getString("MAPHONG"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void DICHVU(){
        String sql = "select * from DICHVU";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                jComboBox2.addItem(rs.getString("MADV"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void KHACHHANG(){
        String sql = "select * from KHACHHANG";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                cbb_KhachHang.addItem(rs.getString("MAKH"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        DefaultTableModel d1 = (DefaultTableModel)tbl_DSThuePhong.getModel();
        int SelectIndex = tbl_DSThuePhong.getSelectedRow();
      
        String MaPhong = d1.getValueAt(SelectIndex,0 ).toString();
            
        String NgayDen = dateThue.getDate().toString();
        String NgayDi = dateTra.getDate().toString();
        String MaDV = jComboBox2.getSelectedItem().toString();
        String MaKH = cbb_KhachHang.getSelectedItem().toString();
                
        if(jTextArea2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Hãy chú thích 1 điều gì đó");
        //thông báo nếu password trống    
        }else{
            try {
                pst = con.prepareStatement("update PHONG set NGAYTHUE=?, NGAYTRAPHONG=?, MADV=?, MAKH=? where MAPHONG=? ");
                pst.setString(1, NgayDen);
                pst.setString(2, NgayDi);
                pst.setString(3, MaDV);
                pst.setString(4, MaKH);
                pst.setString(5, MaPhong);
                int k = pst.executeUpdate();

                if(k==1)
                {
                    
                    cbxMaPhong.setSelectedItem(false);
                    cbb_KhachHang.setSelectedItem(false);
                    jComboBox2.setSelectedItem(false);
                    CrudTable();

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Dat phong that bai");
                }

            } catch (SQLException ex) {
                Logger.getLogger(DatPhong.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
        
        
    }//GEN-LAST:event_btnDatPhongActionPerformed

    private void cbxMaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMaPhongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatPhong;
    public javax.swing.JComboBox<String> cbb_KhachHang;
    private javax.swing.JComboBox<String> cbxMaPhong;
    private com.toedter.calendar.JDateChooser dateThue;
    private com.toedter.calendar.JDateChooser dateTra;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_DSThuePhong;
    private javax.swing.JLabel ngayra;
    private javax.swing.JLabel ngaythue;
    private javax.swing.JLabel phong;
    private javax.swing.JLabel phong1;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnl2;
    public javax.swing.JTable tbl_DSThuePhong;
    private javax.swing.JLabel tenkh;
    private javax.swing.JLabel thuephong;
    // End of variables declaration//GEN-END:variables
}
