    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class KhachHang extends javax.swing.JPanel {
    private JFrame frame;
    DefaultTableModel model;
    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
        Connect();
        CrudTable1();
        CrudTable2();
        updateCombobox();
    }

    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect()
    {
        String connection = "jdbc:sqlserver://DESKTOP-UALN3DS:1433;DatabaseName=QLPKS;user=sa;password=sa;encrypt=true;trustServerCertificate=true";
        try {
            con = DriverManager.getConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(DichVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void CrudTable2()
    {
        try {
            pst = con.prepareStatement("select * from LOAIKH");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData RSM = rs.getMetaData();
            int c;
            c = RSM.getColumnCount();
            
            DefaultTableModel DF = (DefaultTableModel)tblLoaiKH2_146.getModel();
            
            DF.setRowCount(0);
            
            while(rs.next())
            {    
                Vector v2 = new Vector();
                for(int i=1; i <= c; i++)
                {
                    v2.add(rs.getString("MALOAIKH"));
                    v2.add(rs.getString("TENLOAIKH"));
                    v2.add(rs.getString("TIENGIAM"));
                    v2.add(rs.getString("MOTA"));
                    v2.add(rs.getString("TENLOAIKH"));
                }
                DF.addRow(v2);
            }   
        } catch (SQLException ex) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void CrudTable1()
    {
        try {
            pst = con.prepareStatement("select * from KHACHHANG,LOAIKH WHERE KHACHHANG.MALOAIKH=LOAIKH.MALOAIKH;");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData RSM = rs.getMetaData();
            int c;
            c = RSM.getColumnCount();
            
            DefaultTableModel DF = (DefaultTableModel)tblKH_146.getModel();
            
            DF.setRowCount(0);
            
            while(rs.next())
            {    
                Vector v1 = new Vector();
                for(int i=1; i <= c; i++)
                {
                    v1.add(rs.getString("MAKH"));
                    v1.add(rs.getString("TENKH"));
                    v1.add(rs.getString("TUOI"));
                    v1.add(rs.getString("SDT"));
                    v1.add(rs.getString("CMND"));
                    v1.add(rs.getString("QUOCTICH"));
                    v1.add(rs.getString("TENLOAIKH"));
                }
                DF.addRow(v1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void Tuoi(int giatri) {
        int sl = Integer.parseInt(txtTuoi_146.getText());
        sl = sl + (giatri);
        txtTuoi_146.setText(String.valueOf(sl));
    }

    public void search(String str){
        model = (DefaultTableModel) tblKH_146.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tblKH_146.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl = new javax.swing.JPanel();
        pnl2 = new javax.swing.JPanel();
        lbl_LoaiKH = new javax.swing.JLabel();
        cbxMaLoaiKH_146 = new javax.swing.JComboBox<>();
        lbl_TenKH = new javax.swing.JLabel();
        txtHoTen_146 = new javax.swing.JTextField();
        lbl_Tuoi = new javax.swing.JLabel();
        txtTuoi_146 = new javax.swing.JTextField();
        lbl_GioiTinh = new javax.swing.JLabel();
        rabNam_146 = new javax.swing.JRadioButton();
        rabNu_146 = new javax.swing.JRadioButton();
        lbl_SDT = new javax.swing.JLabel();
        txtSoDT_146 = new javax.swing.JTextField();
        lbl_CMND = new javax.swing.JLabel();
        txtCMND_146 = new javax.swing.JTextField();
        btn_Tru = new javax.swing.JButton();
        btn_Cong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtQuocTich_146 = new javax.swing.JTextField();
        pnl_ThemSuaXoa = new javax.swing.JPanel();
        btnSua_146 = new javax.swing.JButton();
        btnThem_146 = new javax.swing.JButton();
        btnXoa_146 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKH_146 = new javax.swing.JTable();
        lbl_TimKiem = new javax.swing.JLabel();
        txtTimKiem_146 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        lbl_LoaiKH2 = new javax.swing.JLabel();
        lbl_TenLoai = new javax.swing.JLabel();
        lbl_TienGiam = new javax.swing.JLabel();
        lbl_MoTa = new javax.swing.JLabel();
        txtTenLoaiKH_146 = new javax.swing.JTextField();
        txtTienGiam_146 = new javax.swing.JTextField();
        lbl_PhanTram = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa_146 = new javax.swing.JTextArea();
        btn_Them2_146 = new javax.swing.JButton();
        btn_Sua2_146 = new javax.swing.JButton();
        btn_Xoa2_146 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLoaiKH2_146 = new javax.swing.JTable();

        pnl.setBackground(new java.awt.Color(255, 204, 204));
        pnl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_LoaiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_LoaiKH.setText("Mã loại khách hàng");

        cbxMaLoaiKH_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxMaLoaiKH_146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaLoaiKH_146ActionPerformed(evt);
            }
        });

        lbl_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenKH.setText("Tên khách hàng");

        txtHoTen_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_Tuoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Tuoi.setText("Tuổi");

        txtTuoi_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTuoi_146.setText("01");

        lbl_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GioiTinh.setText("Giới tính");

        buttonGroup1.add(rabNam_146);
        rabNam_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rabNam_146.setText("Nam");

        buttonGroup1.add(rabNu_146);
        rabNu_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rabNu_146.setText("Nữ");

        lbl_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_SDT.setText("Số điện thoại");

        txtSoDT_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_CMND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_CMND.setText("Số CMND");

        txtCMND_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_Tru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Tru.setText("-");
        btn_Tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TruActionPerformed(evt);
            }
        });

        btn_Cong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Cong.setText("+");
        btn_Cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CongActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quốc tich");

        pnl_ThemSuaXoa.setBackground(new java.awt.Color(153, 153, 255));

        btnSua_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua_146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (1).png"))); // NOI18N
        btnSua_146.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua_146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_146ActionPerformed(evt);
            }
        });

        btnThem_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem_146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus (1).png"))); // NOI18N
        btnThem_146.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem_146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_146ActionPerformed(evt);
            }
        });

        btnXoa_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa_146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete (1).png"))); // NOI18N
        btnXoa_146.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa_146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_146ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ThemSuaXoaLayout = new javax.swing.GroupLayout(pnl_ThemSuaXoa);
        pnl_ThemSuaXoa.setLayout(pnl_ThemSuaXoaLayout);
        pnl_ThemSuaXoaLayout.setHorizontalGroup(
            pnl_ThemSuaXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThemSuaXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem_146)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnSua_146)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa_146)
                .addGap(20, 20, 20))
        );
        pnl_ThemSuaXoaLayout.setVerticalGroup(
            pnl_ThemSuaXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThemSuaXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ThemSuaXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSua_146, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa_146, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem_146, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/winner.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("KHÁCH HÀNG");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("LÀ THƯỢNG ĐẾ !!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_LoaiKH)
                            .addComponent(lbl_TenKH)
                            .addComponent(lbl_GioiTinh)
                            .addComponent(lbl_SDT)
                            .addComponent(lbl_CMND)
                            .addComponent(jLabel1)
                            .addComponent(lbl_Tuoi))
                        .addGap(23, 23, 23)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addComponent(txtTuoi_146, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Tru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Cong))
                            .addComponent(txtQuocTich_146, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtHoTen_146, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxMaLoaiKH_146, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCMND_146, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSoDT_146, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addComponent(rabNam_146)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rabNu_146))))
                    .addComponent(pnl_ThemSuaXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_LoaiKH)
                            .addComponent(cbxMaLoaiKH_146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TenKH)
                            .addComponent(txtHoTen_146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTuoi_146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Tru)
                            .addComponent(btn_Cong)
                            .addComponent(lbl_Tuoi))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_GioiTinh)
                            .addComponent(rabNam_146)
                            .addComponent(rabNu_146))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_SDT)
                            .addComponent(txtSoDT_146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CMND)
                            .addComponent(txtCMND_146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtQuocTich_146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_ThemSuaXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tblKH_146.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Tuổi", "Số điện thoại", "Chứng minh", "Quốc tịch", "Loại khách hàng"
            }
        ));
        tblKH_146.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblKH_146.setGridColor(new java.awt.Color(255, 255, 255));
        tblKH_146.setSelectionBackground(new java.awt.Color(255, 204, 102));
        tblKH_146.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKH_146MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKH_146);

        lbl_TimKiem.setBackground(new java.awt.Color(204, 255, 204));
        lbl_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_TimKiem.setText("  Tìm kiếm thông tin khách hàng !!!");
        lbl_TimKiem.setOpaque(true);

        txtTimKiem_146.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiem_146KeyReleased(evt);
            }
        });

        jSeparator1.setForeground(javax.swing.UIManager.getDefaults().getColor("Menu.selectionBackground"));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_TimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(9, 9, 9))
            .addGroup(pnlLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem_146, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTimKiem_146, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl3.setBackground(new java.awt.Color(255, 204, 204));
        pnl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_LoaiKH2.setBackground(new java.awt.Color(102, 255, 255));
        lbl_LoaiKH2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_LoaiKH2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LoaiKH2.setText("Loại khách hàng");
        lbl_LoaiKH2.setToolTipText("");
        lbl_LoaiKH2.setOpaque(true);

        lbl_TenLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenLoai.setText("Loại khách hàng");

        lbl_TienGiam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TienGiam.setText("Tiền giảm");

        lbl_MoTa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MoTa.setText("Mô tả");

        txtTenLoaiKH_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTienGiam_146.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTienGiam_146.setText("300000");

        lbl_PhanTram.setText("(VNĐ)");

        txtMoTa_146.setColumns(20);
        txtMoTa_146.setRows(5);
        jScrollPane2.setViewportView(txtMoTa_146);

        btn_Them2_146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus (1).png"))); // NOI18N
        btn_Them2_146.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Them2_146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Them2_146ActionPerformed(evt);
            }
        });

        btn_Sua2_146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (1).png"))); // NOI18N
        btn_Sua2_146.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Sua2_146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sua2_146ActionPerformed(evt);
            }
        });

        btn_Xoa2_146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete (1).png"))); // NOI18N
        btn_Xoa2_146.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Xoa2_146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Xoa2_146ActionPerformed(evt);
            }
        });

        tblLoaiKH2_146.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại KH", "Tên loại KH", "Tiền giảm", "Mô tả"
            }
        ));
        tblLoaiKH2_146.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiKH2_146MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLoaiKH2_146);

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_LoaiKH2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(btn_Them2_146)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Sua2_146)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Xoa2_146)
                        .addGap(4, 4, 4))
                    .addComponent(lbl_MoTa)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_TenLoai)
                            .addComponent(lbl_TienGiam))
                        .addGap(18, 18, 18)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenLoaiKH_146, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(txtTienGiam_146, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_PhanTram))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addComponent(lbl_LoaiKH2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenLoaiKH_146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenLoai))
                .addGap(18, 18, 18)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienGiam_146, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_PhanTram)
                    .addComponent(lbl_TienGiam))
                .addGap(18, 18, 18)
                .addComponent(lbl_MoTa)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Them2_146, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa2_146)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(btn_Sua2_146, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Them2_146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Them2_146ActionPerformed
        String TenLoaiKH = txtTenLoaiKH_146.getText();
        String TienGiam = txtTienGiam_146.getText();
        String MoTa = txtMoTa_146.getText();
        if(txtTenLoaiKH_146.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền tên loại khách hàng!");
        //thông báo nếu password trống    
        }else if(txtTienGiam_146.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền số tiền giảm");
        }else{
            try {
                pst = con.prepareStatement("insert into LOAIKH (TENLOAIKH, TIENGIAM, MOTA)values(?,?,?)");
                pst.setString(1, TenLoaiKH);
                pst.setString(2, TienGiam);
                pst.setString(3, MoTa);
                int k = pst.executeUpdate();

                if(k==1)
                {
                    txtTenLoaiKH_146.setText("");
                    txtTienGiam_146.setText("");
                    txtMoTa_146.setText("");
                    txtTenLoaiKH_146.requestFocus();
                    CrudTable2();

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Them dich vu that bai");
                }

            } catch (SQLException ex) {
                Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_Them2_146ActionPerformed

    private void btn_Sua2_146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sua2_146ActionPerformed
        DefaultTableModel d1 = (DefaultTableModel)tblLoaiKH2_146.getModel();
        int SelectIndex = tblLoaiKH2_146.getSelectedRow();
        
        if(SelectIndex==-1){
            JOptionPane.showMessageDialog(this, "Vui long cho dich vu muon sua!!!");
        }else{   
            String maKH = d1.getValueAt(SelectIndex,0 ).toString();
            String TenLoaiKH = txtTenLoaiKH_146.getText();
            String TienGiam = txtTienGiam_146.getText();
            String MoTa = txtMoTa_146.getText();

            try {
                pst = con.prepareStatement("update LOAIKH set TENLOAIKH=?, TIENGIAM=?, MOTA=? where MALOAIKH=?");
                pst.setString(1, TenLoaiKH);
                pst.setString(2, TienGiam);
                pst.setString(3, MoTa);
                pst.setString(4, maKH);
                int k = pst.executeUpdate();

                if(k==1)
                {
                    txtTenLoaiKH_146.setText("");
                    txtTienGiam_146.setText("");
                    txtMoTa_146.setText("");
                    txtTenLoaiKH_146.requestFocus();
                    CrudTable2();
                    btn_Them2_146.setEnabled(true);

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Sua loai khach hang that bai");
                }

            } catch (SQLException ex) {
                Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_Sua2_146ActionPerformed

    private void tblLoaiKH2_146MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiKH2_146MouseClicked
        DefaultTableModel d1 = (DefaultTableModel)tblLoaiKH2_146.getModel();
        int SelectIndex = tblLoaiKH2_146.getSelectedRow();
        
        String maKH = d1.getValueAt(SelectIndex, 0).toString();
 
        txtTenLoaiKH_146.setText(d1.getValueAt(SelectIndex, 1).toString());
        txtTienGiam_146.setText(d1.getValueAt(SelectIndex, 2).toString());
        txtMoTa_146.setText(d1.getValueAt(SelectIndex, 3).toString());
        btn_Them2_146.setEnabled(false);
    }//GEN-LAST:event_tblLoaiKH2_146MouseClicked

    private void btn_Xoa2_146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Xoa2_146ActionPerformed
        DefaultTableModel d1 = (DefaultTableModel)tblLoaiKH2_146.getModel();
        int SelectIndex = tblLoaiKH2_146.getSelectedRow();
        
        if(SelectIndex==-1){
            JOptionPane.showMessageDialog(this, "Vui long cho dich vu muon xoa!!!");
        }else{   
            try {
                String maKH = d1.getValueAt(SelectIndex,0 ).toString();
                pst = con.prepareStatement("delete from LOAIKH where MALOAIKH = ?");
                pst.setString(1, maKH);
                int k = pst.executeUpdate();

                if(k==1)
                {
                    int xoa =JOptionPane.showConfirmDialog(this, "bạn chắc chắn muốn xóa?","", JOptionPane.OK_CANCEL_OPTION);
                    if (xoa == JOptionPane.OK_OPTION) {
                        txtTenLoaiKH_146.setText("");
                        txtTienGiam_146.setText("");
                        txtMoTa_146.setText("");
                        txtTenLoaiKH_146.requestFocus();
                        CrudTable2();
                        btn_Them2_146.setEnabled(true);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Sua loai khach hang that bai");
                }

            } catch (SQLException ex) {
                Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_Xoa2_146ActionPerformed

    private void updateCombobox(){
        String sql = "select * from LOAIKH";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                cbxMaLoaiKH_146.addItem(rs.getString("MALOAIKH"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnThem_146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_146ActionPerformed
        JRadioButton selectedButton = null;

        if (rabNam_146.isSelected()) {
            selectedButton = rabNam_146;
        } else if  (rabNu_146.isSelected()) {
            selectedButton = rabNu_146;
        }
        
        String TenKH = txtHoTen_146.getText();
        String Cmnd = txtCMND_146.getText();
        String QuocTich = txtQuocTich_146.getText();
        String GioiTinh = selectedButton.getText();
        
        String Tuoi = txtTuoi_146.getText();
        String Sdt = txtSoDT_146.getText();
        String MaLoaiKH = cbxMaLoaiKH_146.getSelectedItem().toString();
        
        if(txtHoTen_146.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền tên khách hàng!");
        //thông báo nếu password trống    
        }else if(txtSoDT_146.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền số điện thoại");
        }else{
            try {
                pst = con.prepareStatement("insert into KHACHHANG (TENKH, CMND, QUOCTICH, GIOITINH, TUOI, SDT, MALOAIKH)values(?, ?, ?, ?, ? ,? ,?)");
                pst.setString(1, TenKH);
                pst.setString(2, Cmnd);
                pst.setString(3, QuocTich);
                pst.setString(4, GioiTinh);
                pst.setString(5, Tuoi);
                pst.setString(6, Sdt);
                pst.setString(7, MaLoaiKH);
                int k = pst.executeUpdate();

                if(k==1)
                {
                    txtHoTen_146.setText("");
                    txtCMND_146.setText("");
                    txtQuocTich_146.setText("");
                    txtTuoi_146.setText("");
                    txtSoDT_146.setText("");
                    rabNam_146.setSelected(false);
                    rabNu_146.setSelected(false);
                    cbxMaLoaiKH_146.setSelectedItem(false);
                    CrudTable1();

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Them dich vu that bai");
                }

            } catch (SQLException ex) {
                Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
    }//GEN-LAST:event_btnThem_146ActionPerformed

    private void btnSua_146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_146ActionPerformed
        DefaultTableModel d1 = (DefaultTableModel)tblKH_146.getModel();
        int SelectIndex = tblKH_146.getSelectedRow();
        
        JRadioButton selectedButton = null;

        if (rabNam_146.isSelected()) {
            selectedButton = rabNam_146;
        } else if  (rabNu_146.isSelected()) {
            selectedButton = rabNu_146;
        }
        String maKH = d1.getValueAt(SelectIndex,0 ).toString();
        
        String TenKH = txtHoTen_146.getText();
        String Cmnd = txtCMND_146.getText();
        String QuocTich = txtQuocTich_146.getText();
        String GioiTinh = selectedButton.getText();
        String Tuoi = txtTuoi_146.getText();
        String Sdt = txtSoDT_146.getText();
        String MaLoaiKH = cbxMaLoaiKH_146.getSelectedItem().toString();
        
        if(txtHoTen_146.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền tên khách hàng!");
        //thông báo nếu password trống    
        }else if(txtSoDT_146.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền số điện thoại");
        }else{
            try {
                pst = con.prepareStatement("update KHACHHANG set TENKH=?, CMND=?, QUOCTICH=?,GIOITINH=?,TUOI=?,  SDT=?, MALOAIKH=? where MAKH=? ");
                pst.setString(1, TenKH);
                pst.setString(2, Cmnd);
                pst.setString(3, QuocTich);
                pst.setString(4, GioiTinh);
                pst.setString(5, Tuoi);
                pst.setString(6, Sdt);
                pst.setString(7, MaLoaiKH);
                pst.setString(8, maKH);
                
                int k = pst.executeUpdate();

                if(k==1)
                {
                    txtHoTen_146.setText("");
                    txtCMND_146.setText("");
                    txtQuocTich_146.setText("");
                    txtTuoi_146.setText("");
                    txtSoDT_146.setText("");
                    rabNam_146.setSelected(false);
                    rabNu_146.setSelected(false);
                    cbxMaLoaiKH_146.setSelectedItem(false);
                    CrudTable1();
                    btn_Them2_146.setEnabled(true);

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Them dich vu that bai");
                }

            } catch (SQLException ex) {
                Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
    }//GEN-LAST:event_btnSua_146ActionPerformed

    private void tblKH_146MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKH_146MouseClicked
        
        
        DefaultTableModel d1 = (DefaultTableModel)tblKH_146.getModel();
        int SelectIndex = tblKH_146.getSelectedRow();
      
        String maKH = d1.getValueAt(SelectIndex, 0).toString();
 
        txtHoTen_146.setText(d1.getValueAt(SelectIndex, 1).toString());
        txtSoDT_146.setText(d1.getValueAt(SelectIndex, 3).toString());
        txtCMND_146.setText(d1.getValueAt(SelectIndex, 4).toString());
        txtQuocTich_146.setText(d1.getValueAt(SelectIndex, 5).toString());
        txtTuoi_146.setText(d1.getValueAt(SelectIndex, 2).toString());
        
    }//GEN-LAST:event_tblKH_146MouseClicked

    private void btn_TruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TruActionPerformed
        if (!txtTuoi_146.getText().equals("1")) {
            Tuoi(-1);
        }
    }//GEN-LAST:event_btn_TruActionPerformed

    private void btn_CongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CongActionPerformed
        Tuoi(1);
    }//GEN-LAST:event_btn_CongActionPerformed

    private void btnXoa_146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_146ActionPerformed
        DefaultTableModel d1 = (DefaultTableModel)tblKH_146.getModel();
        int SelectIndex = tblKH_146.getSelectedRow();
        
        String maKH = d1.getValueAt(SelectIndex,0 ).toString();
        
        if(SelectIndex==-1){
            JOptionPane.showMessageDialog(this, "Vui long cho dich vu muon xoa!!!");
        }else{   
            try {
                
                pst = con.prepareStatement("delete from KHACHHANG where MAKH = ?");
                pst.setString(1, maKH);
                int k = pst.executeUpdate();

                if(k==1)
                {
                    int xoa =JOptionPane.showConfirmDialog(this, "bạn chắc chắn muốn xóa?","", JOptionPane.OK_CANCEL_OPTION);
                    if (xoa == JOptionPane.OK_OPTION) {
                        txtHoTen_146.setText("");
                        txtCMND_146.setText("");
                        txtQuocTich_146.setText("");
                        txtTuoi_146.setText("");
                        txtSoDT_146.setText("");
                        rabNam_146.setSelected(false);
                        rabNu_146.setSelected(false);
                        cbxMaLoaiKH_146.setSelectedItem(false);
                        CrudTable1();
                        btn_Them2_146.setEnabled(true);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Sua loai khach hang that bai");
                }

            } catch (SQLException ex) {
                Logger.getLogger(KhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXoa_146ActionPerformed

    private void txtTimKiem_146KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiem_146KeyReleased
        String  searchString = txtTimKiem_146.getText();
        search(searchString);
    }//GEN-LAST:event_txtTimKiem_146KeyReleased

    private void cbxMaLoaiKH_146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaLoaiKH_146ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMaLoaiKH_146ActionPerformed
                                          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua_146;
    private javax.swing.JButton btnThem_146;
    private javax.swing.JButton btnXoa_146;
    private javax.swing.JButton btn_Cong;
    private javax.swing.JButton btn_Sua2_146;
    private javax.swing.JButton btn_Them2_146;
    private javax.swing.JButton btn_Tru;
    private javax.swing.JButton btn_Xoa2_146;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cbxMaLoaiKH_146;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_CMND;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_LoaiKH;
    private javax.swing.JLabel lbl_LoaiKH2;
    private javax.swing.JLabel lbl_MoTa;
    private javax.swing.JLabel lbl_PhanTram;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_TenKH;
    private javax.swing.JLabel lbl_TenLoai;
    private javax.swing.JLabel lbl_TienGiam;
    private javax.swing.JLabel lbl_TimKiem;
    private javax.swing.JLabel lbl_Tuoi;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl_ThemSuaXoa;
    private javax.swing.JRadioButton rabNam_146;
    private javax.swing.JRadioButton rabNu_146;
    private javax.swing.JTable tblKH_146;
    public javax.swing.JTable tblLoaiKH2_146;
    private javax.swing.JTextField txtCMND_146;
    private javax.swing.JTextField txtHoTen_146;
    private javax.swing.JTextArea txtMoTa_146;
    private javax.swing.JTextField txtQuocTich_146;
    private javax.swing.JTextField txtSoDT_146;
    private javax.swing.JTextField txtTenLoaiKH_146;
    private javax.swing.JTextField txtTienGiam_146;
    private javax.swing.JTextField txtTimKiem_146;
    private javax.swing.JTextField txtTuoi_146;
    // End of variables declaration//GEN-END:variables
}
