/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author GuynIT
 */
public class Phong extends javax.swing.JPanel {

    /**
     * Creates new form Phong
     */
    public Phong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrpnl1_129 = new javax.swing.JScrollPane();
        pnl = new javax.swing.JPanel();
        pnl1_129 = new javax.swing.JPanel();
        jLabel1_129 = new javax.swing.JLabel();
        jPanel2_129 = new javax.swing.JPanel();
        jLabel2_129 = new javax.swing.JLabel();
        jPanel3_129 = new javax.swing.JPanel();
        jLabel3_129 = new javax.swing.JLabel();
        jPanel4_129 = new javax.swing.JPanel();
        jLabel4_129 = new javax.swing.JLabel();
        jPanel5_129 = new javax.swing.JPanel();
        jLabel5_129 = new javax.swing.JLabel();
        jPanel6_129 = new javax.swing.JPanel();
        jLabel6_129 = new javax.swing.JLabel();
        jPanel7_129 = new javax.swing.JPanel();
        jLabel7_129 = new javax.swing.JLabel();
        jPanel8_129 = new javax.swing.JPanel();
        jLabel8_129 = new javax.swing.JLabel();
        jPanel9_129 = new javax.swing.JPanel();
        jLabel9_129 = new javax.swing.JLabel();
        jPanel10_129 = new javax.swing.JPanel();
        jLabel10_129 = new javax.swing.JLabel();
        jPanel11_129 = new javax.swing.JPanel();
        jLabel11_129 = new javax.swing.JLabel();
        jPanel12_129 = new javax.swing.JPanel();
        jLabel12_129 = new javax.swing.JLabel();
        jPanel13_129 = new javax.swing.JPanel();
        jLabel13_129 = new javax.swing.JLabel();
        jPanel14_129 = new javax.swing.JPanel();
        jLabel14_129 = new javax.swing.JLabel();
        jPanel15_129 = new javax.swing.JPanel();
        jLabel15_129 = new javax.swing.JLabel();
        jPanel16_129 = new javax.swing.JPanel();
        jLabel16_129 = new javax.swing.JLabel();
        jPanel17_129 = new javax.swing.JPanel();
        jLabel17_129 = new javax.swing.JLabel();
        jPanel18_129 = new javax.swing.JPanel();
        jLabel18_129 = new javax.swing.JLabel();
        pnl2_129 = new javax.swing.JPanel();
        lbl_129 = new javax.swing.JLabel();
        jTextField1_129 = new javax.swing.JTextField();
        jButton1_129 = new javax.swing.JButton();
        jSeparator1_129 = new javax.swing.JSeparator();
        jPanel19 = new javax.swing.JPanel();
        rab1_129 = new javax.swing.JRadioButton();
        rab2_129 = new javax.swing.JRadioButton();
        btn1_129 = new javax.swing.JButton();
        rab3_129 = new javax.swing.JRadioButton();
        rab4_129 = new javax.swing.JRadioButton();
        btn2_129 = new javax.swing.JButton();
        btn3_129 = new javax.swing.JButton();
        btn4_129 = new javax.swing.JButton();
        btn5_129 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pnl.setBackground(new java.awt.Color(255, 255, 255));

        pnl1_129.setBackground(new java.awt.Color(153, 153, 255));
        pnl1_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl1_129.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel1_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_129.setText("P.100");

        javax.swing.GroupLayout pnl1_129Layout = new javax.swing.GroupLayout(pnl1_129);
        pnl1_129.setLayout(pnl1_129Layout);
        pnl1_129Layout.setHorizontalGroup(
            pnl1_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        pnl1_129Layout.setVerticalGroup(
            pnl1_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1_129, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel2_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel2_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_129.setText("P.101");

        javax.swing.GroupLayout jPanel2_129Layout = new javax.swing.GroupLayout(jPanel2_129);
        jPanel2_129.setLayout(jPanel2_129Layout);
        jPanel2_129Layout.setHorizontalGroup(
            jPanel2_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2_129, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel2_129Layout.setVerticalGroup(
            jPanel2_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2_129, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel3_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel3_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_129.setText("P.102");

        javax.swing.GroupLayout jPanel3_129Layout = new javax.swing.GroupLayout(jPanel3_129);
        jPanel3_129.setLayout(jPanel3_129Layout);
        jPanel3_129Layout.setHorizontalGroup(
            jPanel3_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel3_129Layout.setVerticalGroup(
            jPanel3_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel4_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel4_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_129.setText("P.103");

        javax.swing.GroupLayout jPanel4_129Layout = new javax.swing.GroupLayout(jPanel4_129);
        jPanel4_129.setLayout(jPanel4_129Layout);
        jPanel4_129Layout.setHorizontalGroup(
            jPanel4_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel4_129Layout.setVerticalGroup(
            jPanel4_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel5_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel5_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5_129.setText("P.104");

        javax.swing.GroupLayout jPanel5_129Layout = new javax.swing.GroupLayout(jPanel5_129);
        jPanel5_129.setLayout(jPanel5_129Layout);
        jPanel5_129Layout.setHorizontalGroup(
            jPanel5_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel5_129Layout.setVerticalGroup(
            jPanel5_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel6_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel6_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6_129.setText("P.105");

        javax.swing.GroupLayout jPanel6_129Layout = new javax.swing.GroupLayout(jPanel6_129);
        jPanel6_129.setLayout(jPanel6_129Layout);
        jPanel6_129Layout.setHorizontalGroup(
            jPanel6_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel6_129Layout.setVerticalGroup(
            jPanel6_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel7_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel7_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7_129.setText("P.106");

        javax.swing.GroupLayout jPanel7_129Layout = new javax.swing.GroupLayout(jPanel7_129);
        jPanel7_129.setLayout(jPanel7_129Layout);
        jPanel7_129Layout.setHorizontalGroup(
            jPanel7_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel7_129Layout.setVerticalGroup(
            jPanel7_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel8_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel8_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel8_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8_129.setText("P.107");

        javax.swing.GroupLayout jPanel8_129Layout = new javax.swing.GroupLayout(jPanel8_129);
        jPanel8_129.setLayout(jPanel8_129Layout);
        jPanel8_129Layout.setHorizontalGroup(
            jPanel8_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel8_129Layout.setVerticalGroup(
            jPanel8_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel9_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel9_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9_129.setText("P.108");

        javax.swing.GroupLayout jPanel9_129Layout = new javax.swing.GroupLayout(jPanel9_129);
        jPanel9_129.setLayout(jPanel9_129Layout);
        jPanel9_129Layout.setHorizontalGroup(
            jPanel9_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel9_129Layout.setVerticalGroup(
            jPanel9_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel10_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel10_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel10_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10_129.setText("P.109");

        javax.swing.GroupLayout jPanel10_129Layout = new javax.swing.GroupLayout(jPanel10_129);
        jPanel10_129.setLayout(jPanel10_129Layout);
        jPanel10_129Layout.setHorizontalGroup(
            jPanel10_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel10_129Layout.setVerticalGroup(
            jPanel10_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel11_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel11_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel11_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11_129.setText("P.201");

        javax.swing.GroupLayout jPanel11_129Layout = new javax.swing.GroupLayout(jPanel11_129);
        jPanel11_129.setLayout(jPanel11_129Layout);
        jPanel11_129Layout.setHorizontalGroup(
            jPanel11_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel11_129Layout.setVerticalGroup(
            jPanel11_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel12_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel12_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel12_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12_129.setText("P.200");

        javax.swing.GroupLayout jPanel12_129Layout = new javax.swing.GroupLayout(jPanel12_129);
        jPanel12_129.setLayout(jPanel12_129Layout);
        jPanel12_129Layout.setHorizontalGroup(
            jPanel12_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12_129, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel12_129Layout.setVerticalGroup(
            jPanel12_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel13_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel13_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel13_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13_129.setText("P.202");

        javax.swing.GroupLayout jPanel13_129Layout = new javax.swing.GroupLayout(jPanel13_129);
        jPanel13_129.setLayout(jPanel13_129Layout);
        jPanel13_129Layout.setHorizontalGroup(
            jPanel13_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel13_129Layout.setVerticalGroup(
            jPanel13_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel14_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel14_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel14_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14_129.setText("P.204");

        javax.swing.GroupLayout jPanel14_129Layout = new javax.swing.GroupLayout(jPanel14_129);
        jPanel14_129.setLayout(jPanel14_129Layout);
        jPanel14_129Layout.setHorizontalGroup(
            jPanel14_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel14_129Layout.setVerticalGroup(
            jPanel14_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel15_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel15_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel15_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15_129.setText("P.203");

        javax.swing.GroupLayout jPanel15_129Layout = new javax.swing.GroupLayout(jPanel15_129);
        jPanel15_129.setLayout(jPanel15_129Layout);
        jPanel15_129Layout.setHorizontalGroup(
            jPanel15_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel15_129Layout.setVerticalGroup(
            jPanel15_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel16_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel16_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel16_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16_129.setText("P.204");

        javax.swing.GroupLayout jPanel16_129Layout = new javax.swing.GroupLayout(jPanel16_129);
        jPanel16_129.setLayout(jPanel16_129Layout);
        jPanel16_129Layout.setHorizontalGroup(
            jPanel16_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel16_129Layout.setVerticalGroup(
            jPanel16_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel17_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel17_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel17_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17_129.setText("P.204");

        javax.swing.GroupLayout jPanel17_129Layout = new javax.swing.GroupLayout(jPanel17_129);
        jPanel17_129.setLayout(jPanel17_129Layout);
        jPanel17_129Layout.setHorizontalGroup(
            jPanel17_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel17_129Layout.setVerticalGroup(
            jPanel17_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel18_129.setBackground(new java.awt.Color(153, 153, 255));
        jPanel18_129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18_129.setPreferredSize(new java.awt.Dimension(163, 150));

        jLabel18_129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18_129.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18_129.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18_129.setText("P.204");

        javax.swing.GroupLayout jPanel18_129Layout = new javax.swing.GroupLayout(jPanel18_129);
        jPanel18_129.setLayout(jPanel18_129Layout);
        jPanel18_129Layout.setHorizontalGroup(
            jPanel18_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        jPanel18_129Layout.setVerticalGroup(
            jPanel18_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18_129, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(pnl1_129, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(jPanel7_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(jPanel13_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel15_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel18_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(726, Short.MAX_VALUE))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl1_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel6_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(728, Short.MAX_VALUE))
        );

        scrpnl1_129.setViewportView(pnl);

        pnl2_129.setBackground(new java.awt.Color(255, 255, 255));
        pnl2_129.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_129.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_129.setText("Tìm phòng");

        jTextField1_129.setText("tìm phòng");

        jButton1_129.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon_Search.png"))); // NOI18N
        jButton1_129.setText("Tìm phòng");

        jSeparator1_129.setForeground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout pnl2_129Layout = new javax.swing.GroupLayout(pnl2_129);
        pnl2_129.setLayout(pnl2_129Layout);
        pnl2_129Layout.setHorizontalGroup(
            pnl2_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2_129Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnl2_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1_129, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_129)
                    .addGroup(pnl2_129Layout.createSequentialGroup()
                        .addComponent(jTextField1_129, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1_129)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        pnl2_129Layout.setVerticalGroup(
            pnl2_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2_129Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_129)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_129, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2_129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1_129, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_129))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rab1_129.setText("1 Giường đơn");
        rab1_129.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rab2_129.setText("Khác");
        rab2_129.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn1_129.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon_Loc.png"))); // NOI18N
        btn1_129.setText("LỌC");
        btn1_129.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1_129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_129ActionPerformed(evt);
            }
        });

        rab3_129.setText("1 giường đôi");
        rab3_129.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rab4_129.setText("2 giường đơn");
        rab4_129.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn2_129.setBackground(new java.awt.Color(135, 255, 0));
        btn2_129.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn2_129.setText("Phòng trống");
        btn2_129.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2_129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_129ActionPerformed(evt);
            }
        });

        btn3_129.setBackground(new java.awt.Color(153, 255, 255));
        btn3_129.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn3_129.setText("Đang sử dụng");
        btn3_129.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3_129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_129ActionPerformed(evt);
            }
        });

        btn4_129.setBackground(new java.awt.Color(255, 102, 51));
        btn4_129.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn4_129.setText("Đang dọn");
        btn4_129.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4_129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_129ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn2_129)
                .addGap(18, 18, 18)
                .addComponent(btn3_129)
                .addGap(18, 18, 18)
                .addComponent(btn4_129)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(rab1_129)
                .addGap(18, 18, 18)
                .addComponent(rab4_129)
                .addGap(18, 18, 18)
                .addComponent(rab3_129)
                .addGap(18, 18, 18)
                .addComponent(rab2_129)
                .addGap(18, 18, 18)
                .addComponent(btn1_129)
                .addGap(22, 22, 22))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rab3_129)
                        .addComponent(rab4_129)
                        .addComponent(rab1_129)
                        .addComponent(rab2_129)
                        .addComponent(btn1_129))
                    .addComponent(btn4_129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn3_129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn2_129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btn5_129.setBackground(new java.awt.Color(182, 10, 73));
        btn5_129.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn5_129.setText("Đặt ngay");
        btn5_129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5_129ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrpnl1_129, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnl2_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn5_129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn5_129, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl2_129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrpnl1_129, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn4_129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_129ActionPerformed
    
    }//GEN-LAST:event_btn4_129ActionPerformed

    private void btn3_129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_129ActionPerformed

    }//GEN-LAST:event_btn3_129ActionPerformed

    private void btn2_129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_129ActionPerformed

    }//GEN-LAST:event_btn2_129ActionPerformed

    private void btn1_129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_129ActionPerformed
 
    }//GEN-LAST:event_btn1_129ActionPerformed

    private void btn5_129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5_129ActionPerformed

    }//GEN-LAST:event_btn5_129ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1_129;
    private javax.swing.JButton btn2_129;
    private javax.swing.JButton btn3_129;
    private javax.swing.JButton btn4_129;
    private javax.swing.JButton btn5_129;
    private javax.swing.JButton jButton1_129;
    private javax.swing.JLabel jLabel10_129;
    private javax.swing.JLabel jLabel11_129;
    private javax.swing.JLabel jLabel12_129;
    private javax.swing.JLabel jLabel13_129;
    private javax.swing.JLabel jLabel14_129;
    private javax.swing.JLabel jLabel15_129;
    private javax.swing.JLabel jLabel16_129;
    private javax.swing.JLabel jLabel17_129;
    private javax.swing.JLabel jLabel18_129;
    private javax.swing.JLabel jLabel1_129;
    private javax.swing.JLabel jLabel2_129;
    private javax.swing.JLabel jLabel3_129;
    private javax.swing.JLabel jLabel4_129;
    private javax.swing.JLabel jLabel5_129;
    private javax.swing.JLabel jLabel6_129;
    private javax.swing.JLabel jLabel7_129;
    private javax.swing.JLabel jLabel8_129;
    private javax.swing.JLabel jLabel9_129;
    private javax.swing.JPanel jPanel10_129;
    private javax.swing.JPanel jPanel11_129;
    private javax.swing.JPanel jPanel12_129;
    private javax.swing.JPanel jPanel13_129;
    private javax.swing.JPanel jPanel14_129;
    private javax.swing.JPanel jPanel15_129;
    private javax.swing.JPanel jPanel16_129;
    private javax.swing.JPanel jPanel17_129;
    private javax.swing.JPanel jPanel18_129;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2_129;
    private javax.swing.JPanel jPanel3_129;
    private javax.swing.JPanel jPanel4_129;
    private javax.swing.JPanel jPanel5_129;
    private javax.swing.JPanel jPanel6_129;
    private javax.swing.JPanel jPanel7_129;
    private javax.swing.JPanel jPanel8_129;
    private javax.swing.JPanel jPanel9_129;
    private javax.swing.JSeparator jSeparator1_129;
    private javax.swing.JTextField jTextField1_129;
    private javax.swing.JLabel lbl_129;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnl1_129;
    private javax.swing.JPanel pnl2_129;
    private javax.swing.JRadioButton rab1_129;
    private javax.swing.JRadioButton rab2_129;
    private javax.swing.JRadioButton rab3_129;
    private javax.swing.JRadioButton rab4_129;
    private javax.swing.JScrollPane scrpnl1_129;
    // End of variables declaration//GEN-END:variables
}
