    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author GuynIT
 */
public class KhachHang extends javax.swing.JPanel {

    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        pnl2 = new javax.swing.JPanel();
        lbl_MaKH = new javax.swing.JLabel();
        txt_MaKH = new javax.swing.JTextField();
        lbl_LoaiKH = new javax.swing.JLabel();
        cbb_LoaiKH = new javax.swing.JComboBox<>();
        lbl_TenKH = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JTextField();
        lbl_Tuoi = new javax.swing.JLabel();
        txt_Tuoi = new javax.swing.JTextField();
        btn_ThemLoai = new javax.swing.JButton();
        lbl_GioiTinh = new javax.swing.JLabel();
        rab_Nam = new javax.swing.JRadioButton();
        rab_Nu = new javax.swing.JRadioButton();
        lbl_SDT = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        lbl_CMND = new javax.swing.JLabel();
        txt_CMND = new javax.swing.JTextField();
        btn_Tru = new javax.swing.JButton();
        btn_Cong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pnl_ThemSuaXoa = new javax.swing.JPanel();
        btn_Sua = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KH = new javax.swing.JTable();
        lbl_TimKiem = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_Chon = new javax.swing.JButton();
        pnl3 = new javax.swing.JPanel();
        lbl_LoaiKH2 = new javax.swing.JLabel();
        lbl_MaLoai = new javax.swing.JLabel();
        lbl_TenLoai = new javax.swing.JLabel();
        lbl_TienGiam = new javax.swing.JLabel();
        lbl_MoTa = new javax.swing.JLabel();
        txt_MaLoai = new javax.swing.JTextField();
        txt_TenLoaiKH = new javax.swing.JTextField();
        txt_TiemGiam = new javax.swing.JTextField();
        lbl_PhanTram = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_MoTa = new javax.swing.JTextArea();
        btn_Them2 = new javax.swing.JButton();
        btn_SuaLoai = new javax.swing.JButton();
        btn_XoaLoai = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_LoaiKH = new javax.swing.JTable();

        pnl.setBackground(new java.awt.Color(255, 204, 204));
        pnl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_MaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaKH.setText("Mã khách hàng");

        txt_MaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaKH.setText("KH");

        lbl_LoaiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_LoaiKH.setText("Loại khách hàng");

        cbb_LoaiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenKH.setText("Tên khách hàng");

        txt_TenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_Tuoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Tuoi.setText("Tuổi");

        txt_Tuoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Tuoi.setText("01");
        txt_Tuoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TuoiKeyReleased(evt);
            }
        });

        btn_ThemLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ThemLoai.setText("Thêm mới");
        btn_ThemLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLoaiActionPerformed(evt);
            }
        });

        lbl_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GioiTinh.setText("Giới tính");

        rab_Nam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rab_Nam.setText("Nam");

        rab_Nu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rab_Nu.setText("Nữ");

        lbl_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_SDT.setText("Số điện thoại");

        txt_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_CMND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_CMND.setText("Số CMND");

        txt_CMND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_Tru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Tru.setText("-");
        btn_Tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TruActionPerformed(evt);
            }
        });

        btn_Cong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Cong.setText("+");
        btn_Cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CongActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quốc tich");

        pnl_ThemSuaXoa.setBackground(new java.awt.Color(153, 153, 255));

        btn_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (1).png"))); // NOI18N
        btn_Sua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Sua.setEnabled(false);
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus (1).png"))); // NOI18N
        btn_Them.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete (1).png"))); // NOI18N
        btn_Xoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Xoa.setEnabled(false);
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ThemSuaXoaLayout = new javax.swing.GroupLayout(pnl_ThemSuaXoa);
        pnl_ThemSuaXoa.setLayout(pnl_ThemSuaXoaLayout);
        pnl_ThemSuaXoaLayout.setHorizontalGroup(
            pnl_ThemSuaXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThemSuaXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Them)
                .addGap(18, 18, 18)
                .addComponent(btn_Sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btn_Xoa)
                .addContainerGap())
        );
        pnl_ThemSuaXoaLayout.setVerticalGroup(
            pnl_ThemSuaXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThemSuaXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ThemSuaXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/winner.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("KHÁCH HÀNG");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("LÀ THƯỢNG ĐẾ !!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_MaKH)
                            .addComponent(lbl_LoaiKH)
                            .addComponent(lbl_TenKH)
                            .addComponent(lbl_Tuoi)
                            .addComponent(lbl_GioiTinh)
                            .addComponent(lbl_SDT)
                            .addComponent(lbl_CMND)
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addComponent(txt_Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Tru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Cong))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_TenKH, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbb_LoaiKH, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_MaKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_CMND, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_SDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnl2Layout.createSequentialGroup()
                                        .addComponent(rab_Nam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rab_Nu)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ThemLoai))))
                    .addComponent(pnl_ThemSuaXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_MaKH)
                            .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_LoaiKH)
                            .addComponent(cbb_LoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ThemLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TenKH)
                            .addComponent(txt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Tuoi)
                            .addComponent(txt_Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Tru)
                            .addComponent(btn_Cong))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_GioiTinh)
                            .addComponent(rab_Nam)
                            .addComponent(rab_Nu))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_SDT)
                            .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CMND)
                            .addComponent(txt_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(pnl_ThemSuaXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbl_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH"
            }
        ));
        tbl_KH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_KH.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_KH.setSelectionBackground(new java.awt.Color(255, 204, 102));
        tbl_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_KH);

        lbl_TimKiem.setBackground(new java.awt.Color(204, 255, 204));
        lbl_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_TimKiem.setText("  Tìm kiếm thông tin khách hàng !!!");
        lbl_TimKiem.setOpaque(true);

        txt_TimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TimKiemKeyReleased(evt);
            }
        });

        btn_TimKiem.setBackground(new java.awt.Color(255, 255, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(javax.swing.UIManager.getDefaults().getColor("Menu.selectionBackground"));

        btn_Chon.setBackground(new java.awt.Color(0, 102, 0));
        btn_Chon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Chon.setForeground(new java.awt.Color(255, 255, 255));
        btn_Chon.setText("Chọn");
        btn_Chon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Chon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_TimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Chon, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGap(9, 9, 9))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Chon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl3.setBackground(new java.awt.Color(255, 204, 204));
        pnl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_LoaiKH2.setBackground(new java.awt.Color(102, 255, 255));
        lbl_LoaiKH2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_LoaiKH2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LoaiKH2.setText("Loại khách hàng");
        lbl_LoaiKH2.setToolTipText("");
        lbl_LoaiKH2.setOpaque(true);

        lbl_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaLoai.setText("Mã loại KH");

        lbl_TenLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenLoai.setText("Tên loại KH");

        lbl_TienGiam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TienGiam.setText("Tiền giảm");

        lbl_MoTa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MoTa.setText("Mô tả");

        txt_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_TenLoaiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_TiemGiam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_TiemGiam.setText("300000");
        txt_TiemGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TiemGiamActionPerformed(evt);
            }
        });
        txt_TiemGiam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TiemGiamKeyReleased(evt);
            }
        });

        lbl_PhanTram.setText("(VNĐ)");

        txt_MoTa.setColumns(20);
        txt_MoTa.setRows(5);
        jScrollPane2.setViewportView(txt_MoTa);

        btn_Them2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus (1).png"))); // NOI18N
        btn_Them2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Them2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Them2ActionPerformed(evt);
            }
        });

        btn_SuaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (1).png"))); // NOI18N
        btn_SuaLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_SuaLoai.setEnabled(false);
        btn_SuaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaLoaiActionPerformed(evt);
            }
        });

        btn_XoaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete (1).png"))); // NOI18N
        btn_XoaLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_XoaLoai.setEnabled(false);
        btn_XoaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaLoaiActionPerformed(evt);
            }
        });

        tbl_LoaiKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaLoaiKH", "TenLoaiKH", "TienGiam"
            }
        ));
        tbl_LoaiKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LoaiKHMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_LoaiKH);

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_LoaiKH2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(btn_Them2)
                        .addGap(18, 18, 18)
                        .addComponent(btn_SuaLoai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_XoaLoai))
                    .addComponent(lbl_MoTa)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_MaLoai)
                                    .addComponent(lbl_TienGiam))
                                .addGap(24, 24, 24))
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(lbl_TenLoai)
                                .addGap(18, 18, 18)))
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_MaLoai)
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(txt_TiemGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_PhanTram))
                            .addComponent(txt_TenLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addComponent(lbl_LoaiKH2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(txt_MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TenLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_TenLoai))
                        .addGap(18, 18, 18)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TiemGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_PhanTram)
                            .addComponent(lbl_TienGiam)))
                    .addComponent(lbl_MaLoai))
                .addGap(18, 18, 18)
                .addComponent(lbl_MoTa)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Them2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SuaLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XoaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
    
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed

    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed


    }//GEN-LAST:event_btn_ThemActionPerformed

    private void txt_TuoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TuoiKeyReleased

    }//GEN-LAST:event_txt_TuoiKeyReleased

    private void btn_ThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLoaiActionPerformed

    }//GEN-LAST:event_btn_ThemLoaiActionPerformed

    private void btn_TruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TruActionPerformed

    }//GEN-LAST:event_btn_TruActionPerformed

    private void btn_CongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CongActionPerformed

    }//GEN-LAST:event_btn_CongActionPerformed

    private void txt_TimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimKiemKeyReleased
 
    }//GEN-LAST:event_txt_TimKiemKeyReleased

    private void tbl_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KHMouseClicked
    
    }//GEN-LAST:event_tbl_KHMouseClicked

    private void btn_ChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonActionPerformed

    }//GEN-LAST:event_btn_ChonActionPerformed

    private void txt_TiemGiamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TiemGiamKeyReleased
    
    }//GEN-LAST:event_txt_TiemGiamKeyReleased

    private void btn_Them2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Them2ActionPerformed
  
    }//GEN-LAST:event_btn_Them2ActionPerformed

    private void btn_SuaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaLoaiActionPerformed
  

    }//GEN-LAST:event_btn_SuaLoaiActionPerformed

    private void btn_XoaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaLoaiActionPerformed

    }//GEN-LAST:event_btn_XoaLoaiActionPerformed

    private void tbl_LoaiKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LoaiKHMouseClicked
  
    }//GEN-LAST:event_tbl_LoaiKHMouseClicked

    private void txt_TiemGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TiemGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TiemGiamActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Chon;
    private javax.swing.JButton btn_Cong;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_SuaLoai;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Them2;
    private javax.swing.JButton btn_ThemLoai;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Tru;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XoaLoai;
    public javax.swing.JComboBox<String> cbb_LoaiKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_CMND;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_LoaiKH;
    private javax.swing.JLabel lbl_LoaiKH2;
    private javax.swing.JLabel lbl_MaKH;
    private javax.swing.JLabel lbl_MaLoai;
    private javax.swing.JLabel lbl_MoTa;
    private javax.swing.JLabel lbl_PhanTram;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_TenKH;
    private javax.swing.JLabel lbl_TenLoai;
    private javax.swing.JLabel lbl_TienGiam;
    private javax.swing.JLabel lbl_TimKiem;
    private javax.swing.JLabel lbl_Tuoi;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl_ThemSuaXoa;
    private javax.swing.JRadioButton rab_Nam;
    private javax.swing.JRadioButton rab_Nu;
    private javax.swing.JTable tbl_KH;
    public javax.swing.JTable tbl_LoaiKH;
    private javax.swing.JTextField txt_CMND;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_MaLoai;
    private javax.swing.JTextArea txt_MoTa;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenKH;
    private javax.swing.JTextField txt_TenLoaiKH;
    private javax.swing.JTextField txt_TiemGiam;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_Tuoi;
    // End of variables declaration//GEN-END:variables
}
