/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class CungCapDV extends javax.swing.JPanel {


    public static CungCapDV form;


    public CungCapDV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        lbl_MaDV = new javax.swing.JLabel();
        lbl_TenDV = new javax.swing.JLabel();
        lbl_DonVi = new javax.swing.JLabel();
        lbl_DonGia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_GhiChu = new javax.swing.JTextArea();
        lbl_GhiChu = new javax.swing.JLabel();
        txt_MaDV = new javax.swing.JTextField();
        txt_TenDV = new javax.swing.JTextField();
        txt_DonGia = new javax.swing.JTextField();
        pnl_Nut = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        cbb_DonVi = new javax.swing.JComboBox<>();
        btn_LamMoi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_CungCapDV = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        pnl.setBackground(new java.awt.Color(204, 255, 204));
        pnl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_MaDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MaDV.setText("Mã dịch vụ ");

        lbl_TenDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenDV.setText("Tên dịch vụ");

        lbl_DonVi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DonVi.setText("Đơn vị");

        lbl_DonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DonGia.setText("Đơn giá");

        txt_GhiChu.setColumns(20);
        txt_GhiChu.setRows(5);
        jScrollPane1.setViewportView(txt_GhiChu);

        lbl_GhiChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_GhiChu.setText("Ghi chú");

        txt_MaDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MaDV.setText("DV");
        txt_MaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaDVActionPerformed(evt);
            }
        });

        txt_TenDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_DonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_DonGia.setText("0");
        txt_DonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DonGiaKeyReleased(evt);
            }
        });

        pnl_Nut.setBackground(new java.awt.Color(204, 204, 255));
        pnl_Nut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_Cong.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon_server.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Icon_Tru.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_NutLayout = new javax.swing.GroupLayout(pnl_Nut);
        pnl_Nut.setLayout(pnl_NutLayout);
        pnl_NutLayout.setHorizontalGroup(
            pnl_NutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Them)
                .addGap(18, 18, 18)
                .addComponent(btn_Sua)
                .addGap(18, 18, 18)
                .addComponent(btn_Xoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_NutLayout.setVerticalGroup(
            pnl_NutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_NutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_NutLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnl_NutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them)
                            .addComponent(btn_Xoa)))
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        cbb_DonVi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon_Reload.png"))); // NOI18N
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_GhiChu)
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_MaDV)
                                    .addComponent(lbl_TenDV)
                                    .addComponent(lbl_DonVi)
                                    .addComponent(lbl_DonGia))
                                .addGap(45, 45, 45)
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_MaDV)
                                    .addComponent(txt_TenDV)
                                    .addComponent(txt_DonGia)
                                    .addComponent(cbb_DonVi, 0, 164, Short.MAX_VALUE)))
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addComponent(pnl_Nut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_LamMoi)))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaDV)
                    .addComponent(txt_MaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenDV)
                    .addComponent(txt_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_DonVi)
                    .addComponent(cbb_DonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DonGia)
                    .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_GhiChu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Nut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        tbl_CungCapDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Đơn vị", "Đơn giá"
            }
        ));
        tbl_CungCapDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_CungCapDVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_CungCapDV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaDVActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed

    }//GEN-LAST:event_btn_ThemActionPerformed

    private void tbl_CungCapDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_CungCapDVMouseClicked

    }//GEN-LAST:event_tbl_CungCapDVMouseClicked

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed

    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
 
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
       
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void txt_DonGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DonGiaKeyReleased
       
    }//GEN-LAST:event_txt_DonGiaKeyReleased
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbb_DonVi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_DonGia;
    private javax.swing.JLabel lbl_DonVi;
    private javax.swing.JLabel lbl_GhiChu;
    private javax.swing.JLabel lbl_MaDV;
    private javax.swing.JLabel lbl_TenDV;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnl_Nut;
    private javax.swing.JTable tbl_CungCapDV;
    private javax.swing.JTextField txt_DonGia;
    private javax.swing.JTextArea txt_GhiChu;
    private javax.swing.JTextField txt_MaDV;
    private javax.swing.JTextField txt_TenDV;
    // End of variables declaration//GEN-END:variables
}
